import { computed, onMounted, onUnmounted, ref } from 'vue'

import html2canvas from 'html2canvas'
import { NAutoComplete, NButton, NInput, useDialog, useMessage } from 'naive-ui'
import { storeToRefs } from 'pinia'
import { useRoute } from 'vue-router'

import HeaderComponent from './components/Header/index.vue'
import Introduce from './components/introduce/Introduce.vue'
import { useChat } from './hooks/useChat'
import { useScroll } from './hooks/useScroll'
import { useUsingContext } from './hooks/useUsingContext'

import { fetchChatAPIProcess, fetchChatTitle } from '@/api'
import { HoverButton, SvgIcon } from '@/components/common'
import Message from '@/components/Message/index.vue'
import { useBasicLayout } from '@/hooks/useBasicLayout'
import { useI18n } from '@/locales'
import { useChatStore, usePromptStore, useUserStore } from '@/store'
import { isDev, isNull } from '@/utils/is'